name: build

on:
  push:
    tags: ['*']
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  WASM_BUILD_TYPE: MinSizeRel

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: emscripten-core/setup-emsdk@v15
      - name: Configure project
        run: |
          cmake -S . -B ${{github.workspace}}/build_smol -DCMAKE_BUILD_TYPE=${{env.WASM_BUILD_TYPE}} \
          -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/tguy_install" \
          -DTGUY_WASM_LIB=ON \
          -DTGUY_UNICODE_LIBRARY=none \
          -DTGUY_WASM_ONLY_BINDINGS=ON
          cmake -S . -B ${{github.workspace}}/build_big -DCMAKE_BUILD_TYPE=${{env.WASM_BUILD_TYPE}} \
          -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/tguy_big_install" \
          -DTGUY_WASM_LIB=ON \
          -DTGUY_UNICODE_LIBRARY=utf8proc \
          -DTGUY_WASM_ONLY_BINDINGS=ON

      - name: Install artifacts
        run: |
          cmake --build ${{github.workspace}}/build_smol --target install
          cmake --build ${{github.workspace}}/build_big --target install
          cp ${{github.workspace}}/tguy_big_install/lib/libtguy.wasm ${{github.workspace}}/tguy_big_install/lib/libtguy_big.wasm
      - name: Publish Release if ref is a release tag
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            ${{github.workspace}}/tguy_install/lib/libtguy.js
            ${{github.workspace}}/tguy_install/lib/libtguy.wasm
            ${{github.workspace}}/tguy_big_install/lib/libtguy_big.wasm